# Numpy példák

In [1]:
import numpy as np
print(np.__version__)

1.21.5


In [2]:
tömb = np.array([3, 2, 7, 5, 4])
tömb

array([3, 2, 7, 5, 4])

In [3]:
type(tömb)

numpy.ndarray

In [4]:
for elem in tömb:
    print(elem)

3
2
7
5
4


In [5]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [6]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
5 * np.ones(4)

array([5., 5., 5., 5.])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
nulla_dimenzió = np.array(5)
print(nulla_dimenzió)
print(np.ndim(nulla_dimenzió))

5
0


In [13]:
egy_dimenzió = np.array([1, 2, 3, 4])
print(egy_dimenzió)
print(np.ndim(egy_dimenzió))

[1 2 3 4]
1


In [14]:
kettő_dimenzió = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(kettő_dimenzió)
print(np.ndim(kettő_dimenzió))

[[1 2 3 4]
 [5 6 7 8]]
2


In [15]:
három_dimenzió = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(három_dimenzió)
print(np.ndim(három_dimenzió))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [16]:
np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
tömb = np.array([3, 2, 7, 5, 4])
tömb[2]

7

In [19]:
tömb[1] = 4
tömb

array([3, 4, 7, 5, 4])

In [20]:
kettő_dimenzió = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
kettő_dimenzió

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
kettő_dimenzió[1]

array([5, 6, 7, 8])

In [22]:
kettő_dimenzió[1, 2]

7

In [23]:
kettő_dimenzió[1, :]

array([5, 6, 7, 8])

In [24]:
kettő_dimenzió[:, 2]

array([ 3,  7, 11])

In [25]:
kettő_dimenzió[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [26]:
kettő_dimenzió[0:1]

array([[1, 2, 3, 4]])

In [27]:
tömb = np.array([3, 2, 7, 5, 4])
tömb.dtype

dtype('int32')

In [28]:
tömb = np.array([3, 2, 7, 5, 4], dtype='int64')
tömb.dtype

dtype('int64')

In [29]:
szöveg_tömb = np.array(['3', '2', '5'])
szám_tömb = szöveg_tömb.astype(int)
print(szám_tömb)
print(szám_tömb.dtype)

[3 2 5]
int32


In [30]:
dátum = np.datetime64('2022-09-18')
dátum

numpy.datetime64('2022-09-18')

In [31]:
dátum + np.timedelta64(2, 'D')

numpy.datetime64('2022-09-20')

In [32]:
np.array(['2022-09-15', '2022-09-18', '2022-09-21'], dtype='datetime64')

array(['2022-09-15', '2022-09-18', '2022-09-21'], dtype='datetime64[D]')

In [33]:
np.arange('2022-09-17', '2022-09-20', dtype='datetime64')

array(['2022-09-17', '2022-09-18', '2022-09-19'], dtype='datetime64[D]')

In [34]:
tömb = np.array([3, 2, 5])
nézet = tömb
nézet[1] = 4
print(tömb)
print(nézet)

[3 4 5]
[3 4 5]


In [35]:
tömb = np.array([3, 2, 5])
másolat = tömb.copy()
másolat[1] = 4
print(tömb)
print(másolat)

[3 2 5]
[3 4 5]


In [36]:
tömb = np.array([3, 2, 5])
nézet = tömb.view()
nézet[1] = 4
print(tömb)
print(nézet)

[3 4 5]
[3 4 5]


In [37]:
tömb1 = np.array([1, 2, 3])
tömb2 = np.array([4, 5, 6])
tömb3 = np.array([7, 8, 9])
np.concatenate((tömb1, tömb2, tömb3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.hstack((tömb1, tömb2, tömb3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.vstack((tömb1, tömb2, tömb3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
np.dstack((tömb1, tömb2, tömb3))

array([[[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]])

In [41]:
mátrix1 = np.array([[1, 2], [3, 4]])
mátrix2 = np.array([[5, 6], [7, 8]])
np.concatenate((mátrix1, mátrix2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
np.vstack((mátrix1, mátrix2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [43]:
np.hstack((mátrix1, mátrix2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [44]:
np.dstack((mátrix1, mátrix2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [45]:
tömb = np.array([1, 2, 3, 4, 5, 6])
np.array_split(tömb, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [46]:
mátrix = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(mátrix, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [47]:
np.array_split(mátrix, 3, axis=1)

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]),
 array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]),
 array([], shape=(6, 0), dtype=int32)]

In [48]:
tömb = np.array([4, 2, 7, 5, 3])
tömb[np.where(tömb > 3)]

array([4, 7, 5])

In [49]:
tömb > 3

array([ True, False,  True,  True, False])

In [50]:
tömb[tömb > 3]

array([4, 7, 5])

In [51]:
tömb[(tömb > 3) & (tömb % 2 == 1)]

array([7, 5])

In [52]:
tömb[(tömb > 3) | (tömb % 2 == 1)]

array([4, 7, 5, 3])

In [53]:
tömb[~(tömb > 3)]

array([2, 3])

In [54]:
tömb = np.array([4, 2, 7, 5, 3])
tömb.sort()
tömb

array([2, 3, 4, 5, 7])

In [55]:
tömb1 = np.array([4, 2, 6, 5, 3])
tömb2 = np.array([2, 3, 3, 1, 6])
tömb1 + tömb2

array([6, 5, 9, 6, 9])

In [56]:
2 * tömb1

array([ 8,  4, 12, 10,  6])

In [57]:
5 * tömb1 - tömb2 ** 2

array([ 16,   1,  21,  24, -21])

In [58]:
# 1 / 0

In [59]:
np.array([0, 1, -1, 6]) / np.array([0, 0, 0, 2])

C:\Users\CsabaFarago\AppData\Local\Temp\ipykernel_16368\810533697.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 6]) / np.array([0, 0, 0, 2])
C:\Users\CsabaFarago\AppData\Local\Temp\ipykernel_16368\810533697.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 6]) / np.array([0, 0, 0, 2])


array([ nan,  inf, -inf,   3.])

In [60]:
tömb1 = np.array([4, 2, 6, 5, 3])
tömb2 = np.array([2, 3, 3, 1, 6])
np.add(tömb1, tömb2)

array([6, 5, 9, 6, 9])

In [61]:
np.sum([tömb1, tömb2])

35

In [62]:
print(type(np.add))
print(type(np.sum))

<class 'numpy.ufunc'>
<class 'function'>


In [63]:
np.subtract(np.multiply(2, tömb1), tömb2)

array([6, 1, 9, 9, 0])

In [64]:
np.around(np.sin(np.pi * np.arange(13) / 12), 3)

array([0.   , 0.259, 0.5  , 0.707, 0.866, 0.966, 1.   , 0.966, 0.866,
       0.707, 0.5  , 0.259, 0.   ])

In [65]:
def saját_művelet(x, y):
    return 2 * x - y
 
saját_univerzális_művelet = np.frompyfunc(saját_művelet, 2, 1)
saját_univerzális_művelet(tömb1, tömb2)

array([6, 1, 9, 9, 0], dtype=object)

In [66]:
np.random.seed(197777)

In [67]:
np.random.rand()

0.9594203957872212

In [68]:
np.random.rand(5)

array([0.74167017, 0.64522936, 0.72300508, 0.37392376, 0.29038946])

In [69]:
np.random.randint(low=1, high=7, size=[2, 3])

array([[3, 4, 1],
       [6, 3, 2]])

In [70]:
tömb = np.array([1, 2, 3, 4, 5, 6])
np.random.shuffle(tömb)
tömb

array([3, 2, 1, 4, 6, 5])

In [71]:
tömb = np.array([1, 2, 3, 4, 5, 6])
kevert = np.random.permutation(tömb)
print(tömb)
print(kevert)

[1 2 3 4 5 6]
[3 2 4 1 5 6]


In [72]:
np.random.normal(loc=100, scale=15, size=5)

array([ 70.21962162,  83.36455224,  92.01412882, 102.56724918,
       105.22741425])

In [73]:
np.random.binomial(n=10, p=0.5, size=5)

array([4, 1, 8, 3, 4])

In [74]:
np.random.poisson(lam=4, size=10)

array([3, 3, 3, 6, 8, 6, 3, 6, 4, 4])

In [75]:
np.random.uniform(low=1, high=4, size=5)

array([3.9524789 , 1.8798908 , 2.99425885, 1.32248589, 3.49495891])

In [76]:
np.random.exponential(scale=3, size=5)

array([2.07663545, 2.40427867, 1.29314979, 0.0396423 , 0.54592788])

In [77]:
tömb1 = np.array([[1, 2], [3, 4]])
tömb2 = np.array([[5, 6], [7, 8]])
tömb1 @ tömb2

array([[19, 22],
       [43, 50]])

In [78]:
from numpy import linalg
mátrix = np.array([[-6, 3], [4, 5]])
sajátértékek, sajátvektorok = linalg.eig(mátrix)

In [79]:
sajátértékek, sajátvektorok

(array([-7.,  6.]),
 array([[-0.9486833 , -0.24253563],
        [ 0.31622777, -0.9701425 ]]))

In [80]:
mátrix @ sajátvektorok

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])

In [81]:
sajátértékek * sajátvektorok

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])